### ISSUE TITLE
CSS clip property has been deprecated

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-normalise#33]
## What

Remove [`clip`](https://github.com/Financial-Times/o-normalise/blob/bca3c6904f4dde4238749baa599101f979072932/src/scss/_mixins.scss#L5) from codebase, as it has been deprecated. The suggestion is to replace it with [`clip-path`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)

**Comment by notlee** [comment]
Although not breaking this is to be addressed as part of the breaking cascade. Closing to keep track of progress. 

Related issue: https://github.com/Financial-Times/o-normalise/issues/44
Related PR: https://github.com/Financial-Times/o-normalise/pull/48
