### ISSUE TITLE
Support for focus-visible polyfill v5

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/o-normalise#41]
## What

The [focus visible polyfill](http://npmjs.com/package/focus-visible) recommended for use by this component was recently updated from v4 to v5.

Version 5 of the package supports shadow DOM and it's implementation has changed slightly. It will now add classes to the document root (`<html>`) rather than the document body.

## Details

I think o-normalise needs a small tweak to be compatible with both v4 and v5 of the focus visible polyfill package.

**Comment by notlee** [comment]
This is done, to be released as part of the breaking cascade.

Related issue: #44
Related PR: https://github.com/Financial-Times/o-normalise/pull/45

**Comment by notlee** [comment]
Closing to keep track of progress, v2 will include this
